### ISSUE TITLE
Dial URL

### ISSUE THREAD

**Issue by revis3d** [tfreier/desktop-crm#2]
Hi Till, nice project.
What would the dial URL commonly look like?
Is it possible to add more columns, e.g. Calls tab -> name and account of the callee?
Thanks.

**Comment by tfreier** [comment]
Hi @revis3d. thank you for your feedback. Regarding the dial URL it depends on your phone. I use Yealink phones and depending on the generation of the phone the URLs are the following:

```
http://<your-phone-ip>/cgi-bin/ConfigManApp.com?number=$0 (for newer phones) 
http://admin:admin@<your-phone-ip>/servlet?number=$0 (for older phones)
```

If you have a Yealink phone as well. You have to allow remote control in your phone settings under Features > Remote Control. 

I will look into the call columns. It doesn't sound like it would be too difficult.

**Comment by revis3d** [comment]
Yes, thank you, that should be working. I have a SNOM phone. I switched from SugarCRM to SuiteCRM. In Sugar I had a click to dial feature before which made my ASTERISK PBX to call my phone and then dial the remote number for me. It is not working in SuiteCRM anymore after the update. But I wasn't aware that I could remote control the phone directly.

These are the [instructions for SNOM phones](http://wiki.snom.com/FAQ/Can_I_control_my_snom_phone_remotely) if anyone else is interested.


While you're at it:

- In the Calls list it would be nice to have a third color, yellow, for the phonecalls that are due for today.
- Also in the Calls list I am missing the "make call" button.
- When a call comes in it would be great to have an overview of the latest history.

I compiled the latest 2.4 version.

I don't know if my workflow is wrong but I am B2B so I like to see the calls history in the accounts tab. So I relate my calls to the account and add the invitee contact. If it is related to the contact directly I cannot see the call in the accounts history tab. Of course this does not work for leads. What do you think?

Keep up the good work.

**Comment by tfreier** [comment]
@revis3d, that's great feedback, thank you! 

a) changes
I added the name of the parent entity, added the call button and matched the colors to the task list. these things were all pretty simple and make complete sense. the reason why I haven't done that yet is because we do not use use calls like we use tasks which brings us to your workflow question...

b) b2b workflow
We do b2b as well and I specifically developed the tool for our in house use. There are a couple things we might be doing differently. However, they make sense for most people, I believe:

1) We do not schedule call in advance. We only create tasks even if we want to call a person. The call entities we only use to log the actual call. If it's something where we would like to send out invites we use the meeting feature for that. It makes a lot of sense for us because we track what needs to happen as a task and the calls are just attempts to close the task. Example: The task reads "schedule meeting with VP" and the calls all look somewhat like that "NA, left VM" or "asked me to call next week". 

2) It makes sense that you would like to associate the call with an account. Here we also do something that might strike you as unusual but it makes the sales workflow more clear: If we convert a lead we always convert it into an opportunity and then we track all communication in the opportunity and the tool does just that. If there is an open opportunity that involves this contact it will log the call under that opportunity automatically. 

3) Taking this in consideration I enforced the following rule: Every open lead or opportunity must have a follow up task or meeting. This means if an open lead (not dead or converted) doesn't have a task scheduled the tool will remind you to schedule one. Because even if you just left a voice mail you can still decide when to call this lead again. Even if you want to push it two weeks out you can still schedule a task. Before we did that, we would always loose leads and opportunities because people simple forgot about them.  

Anyhow, I pushed the changes to the master branch. I will test them for a bit and then upload a release in the next days.

**Comment by revis3d** [comment]
@tfreier, okay this information renders your tool more useful. Impossible to have found that out by myself. I will try to adopt your workflow and see if that works for me. Thank you for making that clear.

I converted a lead and now I can see that there is more information like contact and account visible for the task. That is nice. This would be great to have for calls (contact, account) and leads (account) as well.

**Comment by revis3d** [comment]
> In the opportunity, how would I change the active contact for a task if I am redirected to another contact?

Stupid me. That was simple, assign a new contact to the task.  😀

**Comment by revis3d** [comment]
Is it easy for you to implement this mechanism for accounts as well? Example: Create a task - > within that task relate it to an account and set the contact. So I could then see "TASK [contact, account]" and then call the contact with the call button and get the tasks logged in accounts.

**Comment by tfreier** [comment]
Technically that is possible the only problem is that you would loose the information of which contact you had the call with which I see as a problem. I have had the same issue that I would like to see all communication within the account but at the same time I would like to log who the call was with. Maybe that would be an enhancement that should be requested in SuiteCRM. They could more easily show contact activity within the account instead of only showing what was specifically assigned to the account. 

However, if you would like to log the call to the account you can do that by clicking the ... button in the call window and then search and select the account in the main window. 

Regarding the contact info for tasks I think this is a good idea. I will look into that next week.

**Comment by revis3d** [comment]
But SuiteCRM does allow that already. Every task (note, etc.) has a _related to_ field and also a _contact_ (or contact name) field. If you set the account as _related to_ and the contact as _contact_ it appears as a task in accounts and you still have the contact available.

**Comment by tfreier** [comment]
@revis3d Alright, that's a valid point! ;)
I'll look into making that change today.

**Comment by tfreier** [comment]
Alright, I published an RC release. Please let me know if you find any issues. 

https://github.com/tfreier/desktop-crm/releases/tag/2.5-RC
